### ISSUE TITLE
MQTT stops picking up new values after ~4days

### ISSUE THREAD

**Issue by mlebaugh** [cbpowell/SenseLink#12]
Currently mqtt stops picking up new values from the mqtt host after about 4 days. I've had this happen a few times now. When it does happen, senselink continues to report the old values to sense. Restarting the container resolves the issue quickly. I'm currently working to figure out the cause, but have limited time. In the meantime I've setup a cron task to restart the container. 

I'll have more time next weekend to troubleshoot, I'll put the container in debug and disable the cron task bouncing it on Wednesday to try to reproduce the issue on the weekend. Any suggestions to troubleshoot are welcome.

**Comment by cbpowell** [comment]
Thanks for the heads up once again - I still don't have any power-reporting MQTT devices myself, so I'll set up a spoofed device to test I think. I wonder if it's the MQTT library dropping the connection? Or possibly SenseLink not handling an error thrown by the MQTT library.

Fortunately restarting the container is a reasonable approach as SenseLink depends only on the config (see: people always saying "Docker containers are _supposed_ to be ephemeral!"). But obviously it'd be ideal that SenseLink handles that internally.

**Comment by mlebaugh** [comment]
I was just updating the switch that the pi I'm running this on is connected to, and think I may have realized the issue is on my end. If senselink loses connection to the mqtt server for whatever reason it does not appear to re-establish.

**Comment by cbpowell** [comment]
Good to know, thanks. The intent is the MQTT client would auto reconnect, so I'll do some testing there to see what's up.

**Comment by cbpowell** [comment]
So I tested by just running on my laptop and disconnect/reconnecting Wifi, and was definitely able to see a failure to reconnect. That testing may not exactly replicate your issue on the RPi, but I was able to correct the issue with the MQTT library failing to reconnect in this instance at least, so we'll see.

I'm not _entirely_ sure why it wasn't working, because it brushes up against the limits of my present knowledge of Python async workings (I am a newbie at Python). The issue appears to have been how I had translated the `AsyncExitStack` context manager example from `asyncio-mqtt`, so I brought the code back in line with the example.

I pushed a `1.2.5-beta` tag and Docker build, so pull that one and give it a shot when you have a chance!

**Comment by mlebaugh** [comment]
Pulled the beta, disabled the cronjob restarting the container, and set an alert for if a value gets "stuck". This should allow me to catch if the issue happens again. Will monitor and let you know the results. 

Seems now I need to look into what was causing the connection to the mqtt server to drop, but thats on my end. 

Thanks again for this project!

**Comment by cbpowell** [comment]
I got distracted with other stuff, but just following up - I'm guessing the 1.2.5 beta has been working OK for you? I'll push it to main if so!

**Comment by cbpowell** [comment]
Went ahead and released the beta as 1.2.5, seemed to be working well for me!

**Comment by mlebaugh** [comment]
apologies, for the late responses. Yes i have had no issues with 1.2.5. Thank you again!
